#
# Copyright (C) 2015 The Gravitee team (http://gravitee.io)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
version: '3.5'

networks:
  frontend:
    name: frontend
  storage:
    name: storage

volumes:
  data-elasticsearch:
  data-mongo:

services:
  mongodb:
    image: mongo:${MONGODB_VERSION:-3.6}
    container_name: gio_apim_mongodb
    restart: always
    volumes:
      - data-mongo:/data/db
      - ./logs/apim-mongodb:/var/log/mongodb
    networks:
      - storage

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-5.4.0}
    container_name: gio_apim_elasticsearch
    restart: always
    ports:
      - "9200:9200"
    volumes:
      - data-elasticsearch:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile: 65536
    networks:
      - storage

  gateway:
    image: graviteeio/apim-gateway:${APIM_VERSION:-3.5.11}
    container_name: gio_apim_gateway
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
      - elasticsearch
    volumes:
      - ./logs/apim-gateway:/opt/graviteeio-gateway/logs
      - ./apim-gateway/config/gravitee.yml:/opt/graviteeio-gateway/config/gravitee.yml
      - ./apim-gateway/metrics/:/opt/graviteeio-gateway/metrics/
    environment:
      - gravitee_management_mongodb_uri=mongodb://mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - gravitee_ratelimit_mongodb_uri=mongodb://mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - gravitee_reporters_elasticsearch_endpoints_0=http://elasticsearch:9200
    networks:
      - storage
      - frontend
  
  logstash:
    image: docker.elastic.co/logstash/logstash:${ELASTIC_VERSION:-5.4.0}
    container_name: gio_apim_logstash
    restart: always
    ports:
      - "9600:9600"
    depends_on:
      - elasticsearch
      - gateway
    volumes:
      - ./logstash/gravitee-reporter-conf/logstash/conf/logstash-file.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash/gravitee-reporter-conf/logstash/templates/:/opt/logstash/templates
      - ./apim-gateway/metrics/:/opt/metrics/
      - ./logstash/gravitee-reporter-conf/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
    environment:
      - gravitee_report_path=/opt/metrics/
      - gravitee_templates_path=/opt/logstash/templates
      - MONITORING_ENABLED=false
      - monitoring.elasticsearch.hosts=http://elasticsearch:9200
    networks:
      - storage
      - frontend

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION:-5.4.0}
    container_name: gio_apim_kibana
    restart: always
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - storage
      - frontend

  management_api:
    image: graviteeio/apim-management-api:${APIM_VERSION:-3.5.11}
    container_name: gio_apim_management_api
    restart: always
    ports:
      - "8083:8083"
      - "18083:18083"
    links:
      - mongodb
      - elasticsearch
      - logstash
    depends_on:
      - mongodb
      - elasticsearch
    volumes:
      - ./logs/apim-management-api:/opt/graviteeio-management-api/logs
      - ./apim-api/config/gravitee.yml:/opt/graviteeio-management-api/config/gravitee.yml
      - ./apim-api/config/logback.xml:/opt/graviteeio-management-api/config/logback.xml
    environment:
      - gravitee_management_mongodb_uri=mongodb://mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - gravitee_analytics_elasticsearch_endpoints_0=http://elasticsearch:9200
    networks:
      - storage
      - frontend

  management_ui:
    image: graviteeio/apim-management-ui:${APIM_VERSION:-3.5.11}
    container_name: gio_apim_management_ui
    restart: always
    ports:
      - "8084:8080"
    depends_on:
      - management_api
    environment:
      - MGMT_API_URL=http://localhost:8083/management/organizations/DEFAULT/environments/DEFAULT/
    volumes:
      - ./logs/apim-management-ui:/var/log/nginx
    networks:
      - frontend

  # portal_ui:
  #   image: graviteeio/apim-portal-ui:${APIM_VERSION:-3.5.11}
  #   container_name: gio_apim_portal_ui
  #   restart: always
  #   ports:
  #     - "8085:8080"
  #   depends_on:
  #     - management_api
  #   environment:
  #     - PORTAL_API_URL=http://localhost:8083/portal/environments/DEFAULT
  #   volumes:
  #     - ./logs/apim-portal-ui:/var/log/nginx
  #   networks:
  #     - frontend